### ISSUE TITLE
Move the retrieveImage function into separate module

### ISSUE THREAD

**Issue by dkhd** [dkhd/winterly-tab#1]
This issue is for a beginner who wants to join the Hacktoberfest 2021 as it labelled as `good first issue`.

If you already have some experiences, please ignore this issue 🙂 

---

Please move the `retrieveImage` function to another module. This `retrieveImage` function is being used to retrieve the image from the API.

1. The `retrieveImage` is located at `/src/pages/index.js`
2. Make a new file called `index.js` in directory `/src/util/` (create the directory if it doesn't exist), so the full path will be `/src/util/index.js`
3. Put the `retrieveImage` in the `index.js`, and make it exportable.
4. Import the `retrieveImage` into `/src/pages/index.js`
5. Test it locally to make sure it's working
6. Submit a pull request 🙂

Happy hacking!

**Comment by sano2019** [comment]
Please assign this to me :)

Will the hacktoberfest tag also be added to this? :)

**Comment by dkhd** [comment]
Hi @sano2019 

I've just assigned the issue to you :)

And yes, I'll also add the `hacktoberfest-accepted` label into this.

**Comment by dddqwerty** [comment]
can i do this?

**Comment by dkhd** [comment]
Hi @dddqwerty it's already assigned to @sano2019 

I'll open another `good first issue`, keep watching this page :)

**Comment by dkhd** [comment]
This issue is closed, done in #7 by @sano2019
