### ISSUE TITLE
Doc: Update documentation to add link to the web version

### ISSUE THREAD

**Issue by dkhd** [dkhd/winterly-tab#15]
**Describe the bug**

This is another `good-first-issue` for you 😊 Especially for you who want to contribute to the documentation.

The web version of Winterly Tab is available in [tab.winterly.app](https://tab.winterly.app), but it is still not written in the README.md.

**To Reproduce**
The web version is not written in the README.md.

**Expected behavior**
Put a link to the web version of this project at the README.md.

**Screenshots**
_none_

**Desktop (please complete the following information):**
_all_

**Additional context**

Please follow this guidance to add the link to the web version of this project:

- Put this code **above** the `🌟 Featured by Microsoft` section in the README.md file. I will check the result.

```
---

## 🌏 Web Version

This project is available for you to visit in the web version. This web version will always contain the latest updates & features compared to the browser extension version since updating the browser extension need to be reviewed first by the add-ons or web store administrator, and it takes time.

To see the web version of this project, please visit [tab.winterly.app](https://tab.winterly.app).
```

Have a nice snowy day! And may your coffee always hot ☕️

**Comment by sano2019** [comment]
I'll update this if no one wants it
