### ISSUE TITLE
Create "About" dialog modal

### ISSUE THREAD

**Issue by dkhd** [dkhd/winterly-tab#2]
This is another `good first issue` for newcomers 🔥🔥🔥

---

## Motivation
Because this is an open source project, it would be great to give credit to whoever contribute to this project.

## Description
Please make a dialog modal to show the _About_ section of this project. If you don't know what dialog modal is, [please check these examples](https://tailwindui.com/components/application-ui/overlays/modals).

The dialog modal would be something like this:

| About |
|-|
| Winterly Tab is an open source chrome extension to beautifully change your new tab page with winter-themed background |
| **Maintainer** |
| Diky Hadna [@dkhd](https://github.com/dkhd) |
| **Contributors** |
| Your name [@username](https://github.com/username) |
| Your name [@username](https://github.com/username) |
| Your name [@username](https://github.com/username) |
| _continue the list ..._ |
| [Github](https://github.com/dkhd/winterly-tab) |
| [Close button] |

---

## Rules
1. **Don't:** do not use table (the table above just for layout guidance)
2. **Don't:** do not create new page, the dialog modal should be in the same page with the new tab page, it's dialog modal anyway
3. **Do:** only use [TailwindCSS](https://tailwindcss.com/) for styling
4. **Do:** replace the _Winterly Tab by Diky Hadna_ at the right bottom screen (at the new tab page) with _About_ without changing the current styling (the clickable text should be bolder than non-clickable text)
5. **Do:** If the _About_ text clicked, it should open the dialog modal
6. **Do:** If [Close button] at the dialog modal is clicked, the dialog modal should be closed

---
If you have any question or want to work on this issue, drop your comment below so I can assign this to you 🎉🎉

Happy hacking!

**Comment by dkhd** [comment]
@dddqwerty how about this? Do you want to work on this one?

**Comment by mani-rsg** [comment]
I would like to work on this, can you please assign me this?

**Comment by dkhd** [comment]
Hi @mani-rsg 

I assign this issue to you 🔥🔥🔥

Happy hacking!

**Comment by dhruvjain896** [comment]
Hi @dkhd I would like to work on this repository, could you please open some more good first issue.

**Comment by dkhd** [comment]
Hi @dhruvjain896 sure I will 🔥🔥

Also, if you have an idea, you can also post an issue and we can discuss together.

**Comment by je-poy** [comment]
Hello, can i also work on this issue?

**Comment by je-poy** [comment]
Hi @dkhd , I already created a PR with regards to this, you can assign this to me later :)

**Comment by dkhd** [comment]
Closing as fixed in #13

**Comment by je-poy** [comment]
@dkhd Can I still be working on this one?

**Comment by je-poy** [comment]
You are correct :D
Salamat @dkhd
